# Generated by Django 4.2.25 on 2025-10-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="offer",
            name="description",
            field=models.CharField(max_length=255),
        ),
    ]
